title: Oslobygda kulturlag
description: "Din leverandør av Folkemusikkpøbb i Oslo <3"
lang: nn
url: "https://oslobygda.no"

share_image: "/assets/img/og-oslobygda.jpg"

# Valfritt: gjer fine permalinks for sider
permalink: pretty

sass:
  sass_dir: assets/css